# Temat 4: Biblioteka PyTorch - wprowadzenie

In [18]:
import torch
import numpy as np

print('PyTorch version:', torch.__version__)

np.set_printoptions(precision=3)

PyTorch version: 2.2.1


## Zadanie 4.1

1. (**Generowanie danych**).
Stworzyć tensor `data_tensor` o wymiarach `(5, 3)`, który zawiera losowe liczby z przedziału od 0 do 10. Użyć funkcji `torch.randint()`.

2. (**Podstawowa analiza**).
Oblicz średnią wszystkich elementów w `data_tensor`.
Znaleźć maksymalną wartość w każdym wierszu tego tensora oraz indeksy tych maksymalnych wartości. Wykorzystać do tego celu funkcję `torch.max()` z odpowiednimi argumentami.

3. (**Dalsze przekształcenia**).
Znormalizować
`data_tensor`, tak aby wartości w każdym wierszu sumowały się do 1 (lub do 0, jeśli na wejściu cały wiersz składa się z samych zer). To oznacza, że każdy element wiersza należy podzielić przez sumę elementów w danym wierszu. 
Zadbać o to, aby kod był wykonywalny także we wspomnianym przypadku wiersza złożonego z samych zer, na przykład poprzez dodanie bardzo małej wartości (np. `1e-9`) do mianownika.

4. (**Sortowanie**).
Zaimplementować funkcję, która przyjmie tensor jako argument i zwraca tensor, w którym każdy wiersz jest posortowany rosnąco. Wykorzystać do tego celu funkcję `torch.sort()`.

### 1. Generowanie danych

In [19]:
data_tensor = torch.randint(0, 11, (5, 3))

print(data_tensor)

tensor([[ 8,  7,  7],
        [10,  4,  8],
        [ 0,  6,  8],
        [ 3, 10,  8],
        [ 9,  8,  3]])


### 2. Podstawowa analiza

In [20]:
#data_tensor_mean = torch.mean(data_tensor, axis=0)
#print(data_tensor_mean)

data_tensor_mean_np = np.mean(data_tensor.numpy())
print(data_tensor_mean_np) 

6.6


In [21]:
max_row_values, max_row_values_indices = torch.max(data_tensor, axis=1)

print(max_row_values)
print(max_row_values_indices)

tensor([ 8, 10,  8, 10,  9])
tensor([0, 0, 2, 1, 0])


### 3. Dalsze przekształcenia

In [7]:
data_tensor_normalized = torch.zeros(15)
data_tensor_normalized = data_tensor_normalized.reshape(5, 3)

epsilon = 1e-9

for i, row in enumerate(data_tensor, 0):
    if torch.sum(row) != 0:
        data_tensor_normalized[i] = row / torch.sum(row)
    else:
        data_tensor_normalized[i] = row / (torch.sum(row)+epsilon)


In [8]:
data_tensor_normalized

tensor([[0.6667, 0.0000, 0.3333],
        [0.3913, 0.3043, 0.3043],
        [0.3333, 0.3333, 0.3333],
        [0.3500, 0.4000, 0.2500],
        [0.0000, 0.6667, 0.3333]])

### 4. Sortowanie

In [9]:
def sort_tensor_ascending(data_tensor):
    return torch.sort(data_tensor, axis=1).values

In [10]:
print(data_tensor)

sorted_tensor = sort_tensor_ascending(data_tensor)
print(sorted_tensor)

tensor([[8, 0, 4],
        [9, 7, 7],
        [1, 1, 1],
        [7, 8, 5],
        [0, 2, 1]])
tensor([[0, 4, 8],
        [7, 7, 9],
        [1, 1, 1],
        [5, 7, 8],
        [0, 1, 2]])


## Zadanie 4.2

Stworzyć tensor o wymiarach `(3, 4, 2)` zawierający losowe wartości całkowite z przedziału od 1 do 100 (wyświetlić utworzony tensor). Następnie zamienić w nim drugi wymiar z trzecim (wyświetlić tensor po zamianie) i zmień kształt otrzymanego tensora na `(4, 6)`, łącząc odpowiednio jego elementy (także wyświetlić otrzymany tensor).

In [22]:
data_tensor = torch.randint(0, 101, (3, 4, 2))
print(data_tensor)

tensor([[[34, 52],
         [41, 24],
         [10, 44],
         [86, 31]],

        [[ 8, 52],
         [ 9, 54],
         [91, 57],
         [54, 92]],

        [[11, 30],
         [60, 20],
         [36, 67],
         [93, 61]]])


In [23]:
data_tensor_tr = torch.transpose(data_tensor, 1, 2)
print(data_tensor_tr)


tensor([[[34, 41, 10, 86],
         [52, 24, 44, 31]],

        [[ 8,  9, 91, 54],
         [52, 54, 57, 92]],

        [[11, 60, 36, 93],
         [30, 20, 67, 61]]])


In [24]:
data_tensor_reshape = data_tensor_tr.reshape(4, 6) 
print(data_tensor_reshape)

tensor([[34, 41, 10, 86, 52, 24],
        [44, 31,  8,  9, 91, 54],
        [52, 54, 57, 92, 11, 60],
        [36, 93, 30, 20, 67, 61]])


## Zadanie 4.3

Utworzyć tensor `t` o wymiarach `(6, 10)`, zawierający losowe liczby z przedziału od 0 do 1. Podzielić ten tensora na dwie równe części wzdłuż kolumn, a następnie połączyć te części w jeden tensor wzdłuż nowego wymiaru, tak aby otrzymać tensor o rozmiarze `(2, 6, 5)`. Wyświetlić tensory z wszystkich etapów przekształcenia.
Sprawdzić rozmiar powstałego tensora za pomocą metody `shape`.

In [15]:
t = torch.rand(6,10)
print(t)


tensor([[0.4801, 0.5306, 0.2151, 0.4376, 0.8304, 0.5965, 0.0987, 0.0208, 0.4702,
         0.8074],
        [0.7506, 0.3252, 0.6048, 0.0938, 0.4379, 0.2444, 0.2792, 0.1672, 0.5669,
         0.9671],
        [0.7523, 0.1383, 0.3216, 0.5083, 0.8364, 0.9551, 0.9854, 0.8290, 0.1258,
         0.5909],
        [0.9826, 0.2047, 0.0668, 0.2129, 0.6109, 0.4691, 0.9894, 0.7049, 0.8471,
         0.0193],
        [0.8466, 0.5769, 0.7848, 0.6877, 0.0376, 0.9937, 0.8241, 0.6876, 0.2035,
         0.4977],
        [0.3729, 0.3915, 0.2005, 0.2618, 0.6520, 0.5944, 0.8117, 0.2192, 0.9734,
         0.3543]])


In [16]:
t_splits = torch.chunk(t, chunks=2, dim=1)
print(t_splits)

(tensor([[0.4801, 0.5306, 0.2151, 0.4376, 0.8304],
        [0.7506, 0.3252, 0.6048, 0.0938, 0.4379],
        [0.7523, 0.1383, 0.3216, 0.5083, 0.8364],
        [0.9826, 0.2047, 0.0668, 0.2129, 0.6109],
        [0.8466, 0.5769, 0.7848, 0.6877, 0.0376],
        [0.3729, 0.3915, 0.2005, 0.2618, 0.6520]]), tensor([[0.5965, 0.0987, 0.0208, 0.4702, 0.8074],
        [0.2444, 0.2792, 0.1672, 0.5669, 0.9671],
        [0.9551, 0.9854, 0.8290, 0.1258, 0.5909],
        [0.4691, 0.9894, 0.7049, 0.8471, 0.0193],
        [0.9937, 0.8241, 0.6876, 0.2035, 0.4977],
        [0.5944, 0.8117, 0.2192, 0.9734, 0.3543]]))


In [17]:
S = torch.stack(t_splits, axis=0)
print(S)
print(S.shape)

tensor([[[0.4801, 0.5306, 0.2151, 0.4376, 0.8304],
         [0.7506, 0.3252, 0.6048, 0.0938, 0.4379],
         [0.7523, 0.1383, 0.3216, 0.5083, 0.8364],
         [0.9826, 0.2047, 0.0668, 0.2129, 0.6109],
         [0.8466, 0.5769, 0.7848, 0.6877, 0.0376],
         [0.3729, 0.3915, 0.2005, 0.2618, 0.6520]],

        [[0.5965, 0.0987, 0.0208, 0.4702, 0.8074],
         [0.2444, 0.2792, 0.1672, 0.5669, 0.9671],
         [0.9551, 0.9854, 0.8290, 0.1258, 0.5909],
         [0.4691, 0.9894, 0.7049, 0.8471, 0.0193],
         [0.9937, 0.8241, 0.6876, 0.2035, 0.4977],
         [0.5944, 0.8117, 0.2192, 0.9734, 0.3543]]])
torch.Size([2, 6, 5])
